"""
Django settings for bigstories project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p5krio#@d#h$vu7l=kec(!#u_dy1^9ao--u7iw5pkh&43@#5t)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'main','dash','django_hosts','django.contrib.sitemaps','autoslug','editor','management','business',
]

MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
    
]

ROOT_URLCONF = "bigstories.urls"
DEFAULT_HOST = 'main'
ROOT_HOSTCONF = 'bigstories.hosts'
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / "template",],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.global_context",
                'django.template.context_processors.request'
            ],
        },
    },
]


WSGI_APPLICATION = "bigstories.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bigstorydb',
        'USER': 'minaketan',       # Replace with your PostgreSQL username
        'PASSWORD': 'Mina@2001',  # Your DB password
        'HOST': 'localhost',
        'PORT': '5432',  # Default PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # Replace with your desired timezone
USE_TZ = True  # Ensures timezone-aware datetime handling
USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]  
STATIC_ROOT = '/var/www/bigstory/staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/bigstory/media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # Redis URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'  # Redis result backend (optional)
CELERY_TIMEZONE = 'UTC'
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# Google Analytics 4
GA4_PROPERTY_ID          = '499087182'           # your GA4 property ID (numbers only)
GA4_SERVICE_ACCOUNT_JSON = '/root/Big-Story-Networks-India/ga4_credentials.json'
 
# YouTube Data API v3
YOUTUBE_API_KEY    = 'AIzaSyAfEKDbRztP6ADHtDJ-LcjPiaeBZeTsf9Y'                   # your API key from Google Cloud Console
YOUTUBE_CHANNEL_ID = 'UCVI1UXv98kILXL7-aqzteFg'                     # your YouTube channel ID
 
# Instagram Graph API
INSTAGRAM_ACCESS_TOKEN = 'EAAxxxxxxx...'         # long-lived page access token
INSTAGRAM_ACCOUNT_ID   = '17841xxxxxxxxx'        # Instagram Business account ID

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtpout.secureserver.net"
EMAIL_PORT = 587

EMAIL_HOST_USER = "ceo@bigstorynetwork.com"
EMAIL_HOST_PASSWORD = "Fit@Delhi*2024"

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

DEFAULT_FROM_EMAIL = "CEO Office | BIGSTORY Network <ceo@bigstorynetwork.com>"