# Generated by Django 5.0 on 2025-08-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="scheduled_publish",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
