# Generated by Django 5.0 on 2025-08-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0002_article_scheduled_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="scheduled_publish",
        ),
    ]
