# Generated by Django 5.0 on 2025-08-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0003_remove_article_scheduled_publish"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPageTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="about_us/")),
            ],
        ),
    ]
