# Generated by Django 5.0 on 2025-09-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0004_aboutpageteams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="meta_keywords",
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="article",
            name="meta_title",
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=1500),
        ),
    ]
