# Generated by Django 5.0 on 2025-11-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0005_alter_article_meta_keywords_alter_article_meta_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bigshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bigshot Highlights",
                "verbose_name_plural": "Bigshot Highlights",
            },
        ),
        migrations.CreateModel(
            name="EditorsChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Editor's Choice",
                "verbose_name_plural": "Editor's Choice",
            },
        ),
        migrations.CreateModel(
            name="Exclusives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exclusives",
                "verbose_name_plural": "Exclusives",
            },
        ),
        migrations.CreateModel(
            name="Exclusives2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exclusives2",
                "verbose_name_plural": "Exclusives2",
            },
        ),
        migrations.CreateModel(
            name="LatestArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Latest Articles",
                "verbose_name_plural": "Latest Articles",
            },
        ),
        migrations.CreateModel(
            name="ReelsHighlights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reels Highlights",
                "verbose_name_plural": "Reels Highlights",
            },
        ),
        migrations.CreateModel(
            name="TheChallengers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "TheChallengers Highlights",
                "verbose_name_plural": "TheChallengers Highlights",
            },
        ),
        migrations.CreateModel(
            name="TrendingArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trending Articles",
                "verbose_name_plural": "Trending Articles",
            },
        ),
        migrations.CreateModel(
            name="TrendingBuzz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trending Buzz Videos",
                "verbose_name_plural": "Trending Buzz Videos",
            },
        ),
        migrations.CreateModel(
            name="Unthink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "unthinnk Highlights",
                "verbose_name_plural": "unthinnk Highlights",
            },
        ),
        migrations.RemoveField(
            model_name="comment",
            name="article",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cover",
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
        migrations.RenameField(
            model_name="bstv",
            old_name="meta_keywords",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="bstv",
            name="content",
        ),
        migrations.RemoveField(
            model_name="bstv",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="bstv",
            name="meta_title",
        ),
        migrations.AddField(
            model_name="article",
            name="banner_background_colour",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="article",
            name="remaining_text_colour",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="article",
            name="title_colour",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bstv",
            name="type",
            field=models.CharField(default="Reel", max_length=255),
        ),
        migrations.AlterField(
            model_name="bstv",
            name="title",
            field=models.CharField(max_length=3000),
        ),
        migrations.AddField(
            model_name="bigshot",
            name="highlight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bigshot_highlight",
                to="dash.article",
            ),
        ),
        migrations.AddField(
            model_name="bigshot",
            name="suggested",
            field=models.ManyToManyField(
                blank=True, related_name="Bigshot_Suggestion", to="dash.article"
            ),
        ),
        migrations.AddField(
            model_name="editorschoice",
            name="articles",
            field=models.ManyToManyField(blank=True, to="dash.article"),
        ),
        migrations.AddField(
            model_name="exclusives",
            name="articles",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"status": "Enabled"},
                related_name="exclusive_articles",
                to="dash.article",
            ),
        ),
        migrations.AddField(
            model_name="exclusives",
            name="main_article",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"status": "Enabled"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exclusive_main",
                to="dash.article",
            ),
        ),
        migrations.AddField(
            model_name="exclusives2",
            name="article1",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"status": "Enabled"},
                related_name="article1",
                to="dash.article",
            ),
        ),
        migrations.AddField(
            model_name="exclusives2",
            name="article2",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"status": "Enabled"},
                related_name="article2",
                to="dash.article",
            ),
        ),
        migrations.AddField(
            model_name="exclusives2",
            name="reels",
            field=models.ManyToManyField(blank=True, to="dash.bstv"),
        ),
        migrations.AddField(
            model_name="latestarticles",
            name="article",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"status": "Enabled"},
                related_name="latestArticles",
                to="dash.article",
            ),
        ),
        migrations.AddField(
            model_name="reelshighlights",
            name="reels",
            field=models.ManyToManyField(blank=True, to="dash.bstv"),
        ),
        migrations.AddField(
            model_name="thechallengers",
            name="Challanger_highlight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenger_highlight",
                to="dash.article",
            ),
        ),
        migrations.AddField(
            model_name="thechallengers",
            name="suggested",
            field=models.ManyToManyField(
                blank=True, related_name="Challengers_Suggestion", to="dash.article"
            ),
        ),
        migrations.AddField(
            model_name="trendingarticles",
            name="articles",
            field=models.ManyToManyField(blank=True, to="dash.article"),
        ),
        migrations.AddField(
            model_name="trendingbuzz",
            name="videos",
            field=models.ManyToManyField(blank=True, to="dash.bstv"),
        ),
        migrations.AddField(
            model_name="unthink",
            name="highlight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Unthink_highlight",
                to="dash.article",
            ),
        ),
        migrations.AddField(
            model_name="unthink",
            name="suggested",
            field=models.ManyToManyField(
                blank=True, related_name="Unthink_Suggestion", to="dash.article"
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
