# Generated by Django 5.0 on 2025-11-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0006_bigshot_editorschoice_exclusives_exclusives2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WriterApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("location", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "Student / Campus"),
                            ("fresher", "Fresher (0–1 year)"),
                            ("junior", "1–3 years"),
                            ("mid", "3+ years"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breaking", "Daily news / breaking"),
                            ("explainer", "Explainers & analysis"),
                            ("opinion", "Opinion & columns"),
                            ("features", "Features & longform"),
                            ("script", "Video scripts / BSTV"),
                            ("open", "Open to anything exciting"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("portfolio_links", models.TextField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("beats", models.CharField(blank=True, max_length=300, null=True)),
                ("why_bigstory", models.TextField()),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
