# Generated by Django 5.0 on 2025-12-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0007_writerapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="dash.article",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleHowTo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_name", models.CharField(max_length=300)),
                ("step_text", models.TextField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="howto_steps",
                        to="dash.article",
                    ),
                ),
            ],
        ),
    ]
