# Generated by Django 5.0 on 2026-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0009_author_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tldr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
