# Generated by Django 5.0 on 2026-03-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0010_article_tldr_alter_article_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
