# Generated by Django 5.0 on 2026-03-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0011_article_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tldr_title",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
