# Generated by Django 5.0 on 2026-04-06 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0013_project_task_contributionlog_taskcomment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskBSTV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "bstv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_bstvs",
                        to="dash.bstv",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_bstvs",
                        to="dash.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task BSTV",
                "verbose_name_plural": "Task BSTVs",
                "unique_together": {("task", "bstv")},
            },
        ),
    ]
