# Generated by Django 5.0 on 2026-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0014_taskbstv"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deploy_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="deploy_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("website", "Website"),
                    ("linkedin", "LinkedIn"),
                    ("meta", "Meta"),
                    ("youtube", "YouTube"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
