# Generated by Django 5.0 on 2026-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0015_task_deploy_date_task_deploy_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreenIndiaLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "organisation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "partnership_interest",
                    models.CharField(
                        choices=[
                            (
                                "csr_environment",
                                "CSR Funding — Environmental Campaigns",
                            ),
                            (
                                "csr_women",
                                "CSR Funding — Women Entrepreneurship (Women for Green)",
                            ),
                            (
                                "content_branding",
                                "Content Co-Branding / Green Stories Series",
                            ),
                            (
                                "green_dialogues",
                                "Green Dialogues — Policy Events & Podcasts",
                            ),
                            (
                                "green_action_labs",
                                "Green Action Labs — On-Ground Programs",
                            ),
                            (
                                "green_network",
                                "Green Network — Ecosystem Collaboration",
                            ),
                            ("other", "Other / General Enquiry"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("engaged", "Engaged"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("engagement_notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Green India Lead",
                "verbose_name_plural": "Green India Leads",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
